### ISSUE TITLE
jieba-solr parsedquery empty

### ISSUE THREAD

**Issue by fshare** [sing1ee/jieba-solr#1]
"debug": {
    "rawquerystring": "铝木复合型材",
    "querystring": "铝木复合型材",
    "parsedquery": "",
    "parsedquery_toString": "",

**Comment by rnnnnn** [comment]
@fshare 
嗨~ 我在 solr 4.3.1 遇到一些問題 #7 ，請問可以分享一下你在 solr 4.4.0 還有修改些什麼程式碼嗎
