### ISSUE TITLE
计划什么时候支持solr5

### ISSUE THREAD

**Issue by fshare** [sing1ee/jieba-solr#4]
计划什么时候支持solr5，有规划吗？

**Comment by sing1ee** [comment]
solr5有什么新的feature么？我了解一下，加进来吧

**Comment by sing1ee** [comment]
@fshare 我看了一下，lucene5，变了，我要先了解一下。

**Comment by sing1ee** [comment]
@fshare 5的分词接口变了，我简单写了一个，在solr里试了试，你看看，有没有别的问题 [analyzer-solr](https://github.com/sing1ee/analyzer-solr)
