### ISSUE TITLE
Solr引擎中配置jieba分词器

### ISSUE THREAD

**Issue by MrXiong007** [sing1ee/jieba-solr#5]
我把下载的源码准备打包成一个Jar包，把3个文件夹拷贝进去后存在各种问题：

比如：
类型 JiebaTokenizerFactory 必须实现继承的抽象方法 TokenizerFactory.create（AttributeSource.AttributeFactory, Reader）

比如：
还有像这样的引用找不到资源路径
import org.fnlp.ml.types.Dictionary;
import org.fnlp.nlp.cn.tag.CWSTagger;
import org.fnlp.nlp.corpus.StopWords;

等等

是不是缺少了什么资源包？

**Comment by sing1ee** [comment]
这是少了fnlp分词的jar包，这里可以找到：http://mvnrepository.com/artifact/org.fnlp/fnlp-core/2.0

**Comment by MrXiong007** [comment]
还有一个问题想请教一下，jieba分词器对“英文字符和数字”没有进行进一步分词处理；
我现在想把只要是英文字符和数字一起的字符串，我也想把他分词出来，该如何修改源码？
比如SourceString = “C49D47618”，经过分词，我想得到如下分词：“C”、“49”、“D”、“47618”、“C49D47618”

**Comment by MrXiong007** [comment]
添加了两个Jar包后，错误少了些，但是还是有如下问题：
1、stanford.solr.FnlpAdapter.java  【类型 FnlpAdapter必须实现继承的抽象方法 Iterator<String>.remove（）】

2、stanford.solr.StanfordAdapter.java  【类型 StanfordAdapter 必须实现继承的抽象方法 Iterator<String>.remove（）】

3、jieba.solr.JiebaTokenizer.java 【第42和46行报错：没有为类型 String 定义方法 getToken（），没有为类型 String 定义方法 getToken（）】

这个问题该如何解决呢？

**Comment by sing1ee** [comment]
@MrXiong007 第一个问题，这个分词，需要自己来实现了。第二个你使用过java语言么?

**Comment by MrXiong007** [comment]
恩，
第一个问题，我修改源码的正则表达式已经处理好了：）
第二个问题，我是做C#这一块的，没使用过Java语言，所以不是很了解，但是后来按照Eclipse的提示，@Override一下就好了

非常感谢你，提供了这么好的资源，谢谢！
